export * from './bubbles.service';
import { BubblesService } from './bubbles.service';
export * from './login.service';
import { LoginService } from './login.service';
export * from './seats.service';
import { SeatsService } from './seats.service';
export * from './tables.service';
import { TablesService } from './tables.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [BubblesService, LoginService, SeatsService, TablesService, UsersService];
